import type { FeatureLimitConfig } from '@/hooks/useFeatureLimit';

/**
 * Limites padrão do plano gratuito.
 * Usados como fallback quando a linha ainda não existe em `feature_limits`
 * (a tabela continua sendo a fonte da verdade quando a chave está cadastrada,
 * permitindo que o admin ajuste tudo pela tela de Funções/Assinantes).
 */
export const DEFAULT_FEATURE_LIMITS: FeatureLimitConfig[] = [
  {
    feature_key: 'flashcards',
    label: 'Praticar flashcards',
    description: 'Cards que o usuário free pode estudar por dia',
    category: 'estudo',
    limit_value: 5,
    period: 'daily',
    scope_key: null,
    enabled: true,
    sort_order: 31,
  },
  {
    feature_key: 'questoes',
    label: 'Praticar questões',
    description: 'Questões que o usuário free pode responder por dia',
    category: 'estudo',
    limit_value: 10,
    period: 'daily',
    scope_key: null,
    enabled: true,
    sort_order: 30,
  },
  {
    feature_key: 'questao_funcoes',
    label: 'Funções da questão',
    description: 'Comentário, mini-aula, resumos, termos e pegadinhas — 0 = só assinantes',
    category: 'estudo',
    limit_value: 0,
    period: 'daily',
    scope_key: null,
    enabled: true,
    sort_order: 35,
  },
  {
    feature_key: 'videoaula_funcoes',
    label: 'Funções da videoaula',
    description: 'Flashcards, pegadinhas, resumos, lei seca, termos e questões da aula',
    category: 'estudo',
    limit_value: 0,
    period: 'daily',
    scope_key: null,
    enabled: true,
    sort_order: 36,
  },
  {
    feature_key: 'biblioteca_ler',
    label: 'Ler livro da biblioteca',
    description: '1 livro por mês no plano gratuito (escopo = livro)',
    category: 'biblioteca',
    limit_value: 1,
    period: 'monthly',
    scope_key: 'livro',
    enabled: true,
    sort_order: 50,
  },
  {
    feature_key: 'audioaula_dia',
    label: 'Audioaula (por dia)',
    description: 'Audioaulas que o usuário free pode ouvir por dia',
    category: 'estudo',
    limit_value: 1,
    period: 'daily',
    scope_key: 'audioaula',
    enabled: true,
    sort_order: 37,
  },
  {
    feature_key: 'audioaula_mes',
    label: 'Audioaula (por mês)',
    description: 'Teto mensal de audioaulas no plano gratuito',
    category: 'estudo',
    limit_value: 5,
    period: 'monthly',
    scope_key: 'audioaula',
    enabled: true,
    sort_order: 38,
  },
  {
    feature_key: 'resumo_ver',
    label: 'Abrir resumo jurídico',
    description: 'Resumos que o usuário free pode abrir por dia',
    category: 'ia',
    limit_value: 1,
    period: 'daily',
    scope_key: 'resumo',
    enabled: true,
    sort_order: 63,
  },
  {
    feature_key: 'resumo_download',
    label: 'Baixar/exportar resumo',
    description: '0 = apenas assinantes',
    category: 'ia',
    limit_value: 0,
    period: 'lifetime',
    scope_key: null,
    enabled: true,
    sort_order: 64,
  },
  {
    feature_key: 'lei_seca_praticar',
    label: 'Praticar Lei Seca',
    description: 'Sessões de Lei Seca por dia no plano gratuito',
    category: 'estudo',
    limit_value: 1,
    period: 'daily',
    scope_key: 'parte',
    enabled: true,
    sort_order: 39,
  },
  {
    feature_key: 'apresentacao_ver',
    label: 'Apresentações narradas',
    description: '1 apresentação por dia no plano gratuito (escopo = apresentação)',
    category: 'estudo',
    limit_value: 1,
    period: 'daily',
    scope_key: 'apresentacao',
    enabled: true,
    sort_order: 40,
  },
  {
    feature_key: 'ia_juridica',
    label: 'Chat Jurídico (mensagens)',
    description: 'Mensagens que o usuário free pode enviar (total)',
    category: 'ia',
    limit_value: 1,
    period: 'lifetime',
    scope_key: null,
    enabled: true,
    sort_order: 65,
  },
  {
    feature_key: 'chat_juridico',
    label: 'Chat Jurídico',
    description: 'Mensagens que o usuário free pode enviar (total)',
    category: 'ia',
    limit_value: 1,
    period: 'lifetime',
    scope_key: null,
    enabled: true,
    sort_order: 65,
  },
  {
    feature_key: 'chat_web',
    label: 'Pesquisa na internet no Chat',
    description: '0 = apenas assinantes',
    category: 'ia',
    limit_value: 0,
    period: 'lifetime',
    scope_key: null,
    enabled: true,
    sort_order: 66,
  },
];
