import type { FlashcardsAreaRow, FlashcardsDash } from './flashcardsQueries';

export const FALLBACK_FLASHCARDS_DASH: FlashcardsDash = {
  total_cards: 78077,
  estudados: 0,
  compreendidos: 0,
  a_revisar: 0,
  hoje: 0,
  streak: 0,
  atividade_30d: [],
  temas_criticos: [],
};

export const FALLBACK_FLASHCARDS_AREAS: FlashcardsAreaRow[] = [
  { area: 'Direito Tributário', slug: 'direito-tributario', ordem: 1, total_cards: 20841, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Penal', slug: 'direito-penal', ordem: 2, total_cards: 17558, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Processual Civil', slug: 'direito-processual-civil', ordem: 3, total_cards: 9260, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Civil', slug: 'direito-civil', ordem: 4, total_cards: 7910, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Constitucional', slug: 'direito-constitucional', ordem: 5, total_cards: 5316, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Previdenciário', slug: 'direito-previdenciario', ordem: 6, total_cards: 5262, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Processual do Trabalho', slug: 'direito-processual-do-trabalho', ordem: 7, total_cards: 5141, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito do Trabalho', slug: 'direito-do-trabalho', ordem: 8, total_cards: 4850, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Administrativo', slug: 'direito-administrativo', ordem: 9, total_cards: 4400, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Processual Penal', slug: 'direito-processual-penal', ordem: 10, total_cards: 3400, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Empresarial', slug: 'direito-empresarial', ordem: 11, total_cards: 3330, compreendidos: 0, a_revisar: 0 },
  { area: 'Teoria e Filosofia do Direito', slug: 'teoria-e-filosofia-do-direito', ordem: 12, total_cards: 2360, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Financeiro', slug: 'direito-financeiro', ordem: 13, total_cards: 2260, compreendidos: 0, a_revisar: 0 },
  { area: 'Lei Penal Especial', slug: 'lei-penal-especial', ordem: 14, total_cards: 1570, compreendidos: 0, a_revisar: 0 },
  { area: 'Direitos Humanos', slug: 'direitos-humanos', ordem: 15, total_cards: 1500, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Eleitoral', slug: 'direito-eleitoral', ordem: 16, total_cards: 1380, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Urbanístico', slug: 'direito-urbanistico', ordem: 17, total_cards: 1160, compreendidos: 0, a_revisar: 0 },
  { area: 'Formação Complementar', slug: 'formacao-complementar', ordem: 18, total_cards: 1020, compreendidos: 0, a_revisar: 0 },
  { area: 'Prática Profissional', slug: 'pratica-profissional', ordem: 19, total_cards: 940, compreendidos: 0, a_revisar: 0 },
  { area: 'Políticas Públicas', slug: 'politicas-publicas', ordem: 20, total_cards: 910, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Desportivo', slug: 'direito-desportivo', ordem: 21, total_cards: 820, compreendidos: 0, a_revisar: 0 },
  { area: 'Filosofia do Direito', slug: 'filosofia-do-direito', ordem: 22, total_cards: 760, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Concorrencial', slug: 'direito-concorrencial', ordem: 23, total_cards: 670, compreendidos: 0, a_revisar: 0 },
  { area: 'Revisão OAB', slug: 'revisao-oab', ordem: 24, total_cards: 650, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Internacional Público', slug: 'direito-internacional-publico', ordem: 25, total_cards: 610, compreendidos: 0, a_revisar: 0 },
  { area: 'Português', slug: 'portugues', ordem: 26, total_cards: 600, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Ambiental', slug: 'direito-ambiental', ordem: 27, total_cards: 500, compreendidos: 0, a_revisar: 0 },
  { area: 'Pesquisa Científica', slug: 'pesquisa-cientifica', ordem: 28, total_cards: 200, compreendidos: 0, a_revisar: 0 },
  { area: 'Direito Internacional Privado', slug: 'direito-internacional-privado', ordem: 29, total_cards: 90, compreendidos: 0, a_revisar: 0 },
];
