import {
  Accessibility,
  Baby,
  Banknote,
  BookMarked,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Cannabis,
  Car,
  CircleDollarSign,
  Columns3,
  Cross,
  Drama,
  Droplets,
  Factory,
  FileCheck,
  FileLock,
  FileText,
  FileWarning,
  Gavel,
  Globe,
  GraduationCap,
  HandCoins,
  Handshake,
  HeartPulse,
  Hospital,
  House,
  IdCard,
  Landmark,
  LandPlot,
  Leaf,
  Map,
  Network,
  NotebookPen,
  PiggyBank,
  Plane,
  PocketKnife,
  RadioTower,
  ReceiptText,
  Scale,
  Scroll,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  ShoppingCart,
  Sprout,
  Tractor,
  TreePine,
  Users,
  Vote,
  Wallet,
  Wifi,
  type LucideIcon,
} from 'lucide-react';

/**
 * Mapa de ícones por ID de lei. Usado em listas/categorias do Vade Mecum.
 */
export const LEI_ICON_MAP: Record<string, LucideIcon> = {
  cf88: Landmark,
  cp: PocketKnife,
  cc: House,
  cpc: FileText,
  cpp: ShieldCheck,
  ctn: CircleDollarSign,
  cdc: ShoppingCart,
  clt: Briefcase,
  ctb: Car,
  ce: Vote,
  cpm: Shield,
  cppm: ShieldAlert,
  cflor: TreePine,
  ccom: BriefcaseBusiness,
  cba: Plane,
  cagua: Droplets,
  cmin: LandPlot,
  ctel: RadioTower,
  eca: Baby,
  ei: HeartPulse,
  epd: Accessibility,
  eir: Users,
  ec: Building,
  ed: ShieldX,
  eoab: Scale,
  et: Drama,
  ej: GraduationCap,
  em: Shield,
  eind: Leaf,
  eterra: Tractor,
  emig: Globe,
  eref: Handshake,
  emet: Map,
  emus: Landmark,
  eme: Factory,
  epc: Cross,
  lep: ShieldAlert,
  lmp: ShieldCheck,
  ld: Cannabis,
  loc: Network,
  laa: Gavel,
  lit: RadioTower,
  l8112: IdCard,
  lia: FileWarning,
  nll: ReceiptText,
  lms: FileCheck,
  lacp: Users,
  lje: Handshake,
  lgpd: FileLock,
  mci: Wifi,
  lf: PiggyBank,
  la: Scale,
  li: House,
  lrp: NotebookPen,
  lindb: Scroll,
  ldb: GraduationCap,
  lsus: Hospital,
  lbio: Sprout,
  lrf: Wallet,
  lai: FileText,
  lap: Banknote,
  lpp: Vote,
  lele: Vote,
  lfl: Vote,
  lsa: BriefcaseBusiness,
  lpi: HandCoins,
  constituicao: Landmark,
  codigo: Gavel,
  estatuto: BookMarked,
  jurisprudencia: Scroll,
  'lei-ordinaria': Columns3,
  'lei-especial': Scale,
};

/**
 * Cor padrão (tema verde Vade Mecum) quando não houver cor específica.
 */
export const LEI_ICON_DEFAULT_COLOR = '#16a34a';
