project_id = "dnjrgpldcwcpoywamorr"

[functions.play-billing-webhook]
verify_jwt = false

[functions.apple-billing-webhook]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.narracao]
verify_jwt = false


[functions.forca-gerar-artigo]
enabled = true
verify_jwt = false
import_map = "./functions/forca-gerar-artigo/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/forca-gerar-artigo/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/forca-gerar-artigo/*.html" ]

[functions.get-historico]
enabled = true
verify_jwt = false
import_map = "./functions/get-historico/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-historico/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-historico/*.html" ]

[functions.semantic-search]
enabled = true
verify_jwt = false
import_map = "./functions/semantic-search/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/semantic-search/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/semantic-search/*.html" ]

[functions.apply-vector-migration]
enabled = true
verify_jwt = false
import_map = "./functions/apply-vector-migration/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/apply-vector-migration/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/apply-vector-migration/*.html" ]

[functions.vademecum-embedder]
enabled = true
verify_jwt = false
import_map = "./functions/vademecum-embedder/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/vademecum-embedder/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/vademecum-embedder/*.html" ]

[functions.apply-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/apply-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/apply-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/apply-webhook/*.html" ]

[functions.chat-aula]
enabled = true
verify_jwt = false
import_map = "./functions/chat-aula/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chat-aula/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chat-aula/*.html" ]

[functions.gerar-avaliacao-inteligente]
enabled = true
verify_jwt = false
import_map = "./functions/gerar-avaliacao-inteligente/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gerar-avaliacao-inteligente/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gerar-avaliacao-inteligente/*.html" ]

[functions.admin-sql]
enabled = true
verify_jwt = false
import_map = "./functions/admin-sql/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-sql/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-sql/*.html" ]

[functions.fix-asaas]
enabled = true
verify_jwt = false
import_map = "./functions/fix-asaas/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fix-asaas/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fix-asaas/*.html" ]
