INSERT INTO videoaulas_areas_direito (id, titulo, video_id, area, playlist_id, duracao_segundos, ordem) VALUES
(711, 'Direitos Coletivos | Kultivi - Noções Gerais de Direitos Coletivos | CURSO GRATUITO COMPLETO', 'obFOapa_w4k', 'Direitos Coletivos', 'PL8vXuI6zmpdhekQe3rsbyMgA4yZcj4ISf', 1101, 1),
(712, 'Direitos Coletivos | Kultivi - Classificação e Identificação dos Direitos Coletivos', 'O3nrwrOe7CE', 'Direitos Coletivos', 'PL8vXuI6zmpdhekQe3rsbyMgA4yZcj4ISf', 1683, 2),
(713, 'Direitos Coletivos | Kultivi - Direitos Difusos, Coletivos e Individuais Homogêneos', '-2HMUIb5QcU', 'Direitos Coletivos', 'PL8vXuI6zmpdhekQe3rsbyMgA4yZcj4ISf', 1594, 3),
(714, 'Direitos Coletivos | Kultivi - Proteção dos Direitos Coletivos | CURSO GRATUITO COMPLETO', '5Ixo7dZBVZk', 'Direitos Coletivos', 'PL8vXuI6zmpdhekQe3rsbyMgA4yZcj4ISf', 1759, 4),
(715, 'Reforma Trabalhista | DIREITO - Novidades da Reforma Trabalhista I | CURSO GRATUITO', 'AKLPo6etsjE', 'Direito do Trabalho', 'PL8vXuI6zmpdj9GQbpNQxBhA8r4sJ8tM-3', 1714, 1),
(716, 'Reforma Trabalhista | DIREITO - Novidades da Reforma Trabalhista II | CURSO GRATUITO', 'OHUGLWNZ0tE', 'Direito do Trabalho', 'PL8vXuI6zmpdj9GQbpNQxBhA8r4sJ8tM-3', 1653, 2),
(717, 'Reforma Trabalhista | DIREITO - Novidades da Reforma Trabalhista III | CURSO GRATUITO', 'dELdY9p7KFQ', 'Direito do Trabalho', 'PL8vXuI6zmpdj9GQbpNQxBhA8r4sJ8tM-3', 631, 3),
(718, 'Reforma Trabalhista | DIREITO - Novidades da Reforma Trabalhista IV | CURSO GRATUITO', 'Kt_PKLqTPmw', 'Direito do Trabalho', 'PL8vXuI6zmpdj9GQbpNQxBhA8r4sJ8tM-3', 1001, 4),
(719, 'Reforma Trabalhista | DIREITO - Novidades da Reforma Trabalhista V | CURSO GRATUITO', '3AV-0W-6jz4', 'Direito do Trabalho', 'PL8vXuI6zmpdj9GQbpNQxBhA8r4sJ8tM-3', 760, 5),
(720, 'Reforma Trabalhista | DIREITO - Novidades da Reforma Trabalhista VI | CURSO GRATUITO', 'GI39knQlEFk', 'Direito do Trabalho', 'PL8vXuI6zmpdj9GQbpNQxBhA8r4sJ8tM-3', 1121, 6),
(721, 'Legítima Defesa e Tempo de Pena | Pacote Anticrime | Marcelo Lebre | Aula 1', 'tW4vOwI7jXQ', 'Direito Penal', 'PL8vXuI6zmpdjbogOjoLojdmizBTPmudEv', 1258, 1),
(722, 'Pena de Multa | Pacote Anticrime | Marcelo Lebre | Aula 2', 'Rr5oqwYpr8Q', 'Direito Penal', 'PL8vXuI6zmpdjbogOjoLojdmizBTPmudEv', 773, 2),
(723, 'Livramento Condicional e Prescrição | Pacote Anticrime | Marcelo Lebre | Aula 3', 'nrWu3r9Xhbw', 'Direito Penal', 'PL8vXuI6zmpdjbogOjoLojdmizBTPmudEv', 1052, 3),
(724, 'Efeitos da Condenação e Confisco Alargado | Pacote Anticrime | Marcelo Lebre | Aula 4', 'WKRWGFEEyDc', 'Direito Penal', 'PL8vXuI6zmpdjbogOjoLojdmizBTPmudEv', 1408, 4),
(725, 'Alterações na Parte Especial do Código | Pacote Anticrime | Marcelo Lebre | Aula 5', 'CKqjobv8BLM', 'Direito Penal', 'PL8vXuI6zmpdjbogOjoLojdmizBTPmudEv', 761, 5),
(726, 'Identificação Criminal e Banco de Perfis Genéticos | Pacote Anticrime | Marcelo Lebre | Aula 6', 'cqcbsz6DV9A', 'Direito Penal', 'PL8vXuI6zmpdjbogOjoLojdmizBTPmudEv', 1034, 6),
(727, 'Faltas Disciplinares e R D D | Pacote Anticrime | Marcelo Lebre | Aula 7', 'Xsw8bHAs6S0', 'Direito Penal', 'PL8vXuI6zmpdjbogOjoLojdmizBTPmudEv', 1046, 7),
(728, 'A Nova Progressão de Regimes | Pacote Anticrime | Marcelo Lebre | Aula 8', 'A5J0pPjBPcs', 'Direito Penal', 'PL8vXuI6zmpdjbogOjoLojdmizBTPmudEv', 1280, 8),
(729, 'Saída Temporária | Pacote Anticrime | Marcelo Lebre | Aula 9', 'c0Ar61TpZqs', 'Direito Penal', 'PL8vXuI6zmpdjbogOjoLojdmizBTPmudEv', 329, 9),
(730, 'Legislação Extravagante | Pacote Anticrime | Marcelo Lebre | Aula 10', 'Lo07gauXHQ0', 'Direito Penal', 'PL8vXuI6zmpdjbogOjoLojdmizBTPmudEv', 1085, 10),
(731, 'Normas da Corregedoria | Kultivi - Normas da Corregedoria Geral da Justiça de São Paulo', '3qTw-5S3vsY', 'Direito Administrativo', 'PL8vXuI6zmpdjPGU7_orbGVPXo-HxUv7oE', 1383, 1),
(732, 'Introdução à LGPD', 'ZSAJcss1LDY', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 579, 1),
(733, 'Princípios da LGPD', '5-0eRGU_orE', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 619, 2),
(734, 'Dados Pessoais e Sensíveis', 'EUL1soxd5wE', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 636, 3),
(735, 'Direitos dos Titulares', 'NMHJsDxH9zY', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 506, 4),
(736, 'Obrigações das Empresas', 'Ey-KUmMPnfY', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 585, 5),
(737, 'Estudo de Caso: Direitos dos Titulares', 'PUiuRkfQr_s', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 553, 6),
(738, 'Responsabilidades do Controlador e Operador', '88jNkINYCYw', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 671, 7),
(739, 'Implicações Legais do Descumprimento', 'FfI7Lo0ZqeU', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 729, 8),
(740, 'Estratégias de Adequação à LGPD', 'uDb2JzPVwp8', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 656, 9),
(741, 'Revisão dos Conceitos da LGPD', 'yXiagNFYpPk', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 713, 10),
(742, 'Quiz Final LGPD', 'KDDowVrYw6E', 'Direito Digital e LGPD', 'PL8vXuI6zmpdj9snBEfwTgIxaw4bulA1uT', 462, 11);