const BENEFICIOS: BeneficioTimelineItem[] = [
  {
    id: 'feat_0',
    numero: '01',
    titulo: 'Vade Mecum Inteligente',
    categoria: 'RECURSO INCLUSO',
    badge: 'O Mais Completo',
    cor: 'from-rose-600 to-amber-600',
    icon: Scale,
    funcoes: [
      'Todas as leis federais atualizadas',
      'Busca por termo, número ou assunto',
      'Súmulas Vinculantes e STJ integradas',
      'Leitura formatada e confortável',
      'Histórico de artigos lidos',
      'Organização por áreas do Direito',
      'Comparador de versões da lei',
      'Índice e hierarquia completa'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_1',
    numero: '02',
    titulo: 'IA Jurídica (Horus)',
    categoria: 'RECURSO INCLUSO',
    badge: 'Exclusivo',
    cor: 'from-amber-500 to-orange-500',
    icon: Brain,
    funcoes: [
      'Assistente 24h no WhatsApp',
      'Tira-dúvidas ilimitado sobre leis',
      'Gerador de peças e contratos',
      'Resumos automáticos de artigos',
      'Explicações em linguagem simples',
      'Exemplos práticos instantâneos',
      'Análise de jurisprudência',
      'Sugestão de teses e argumentos'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_2',
    numero: '03',
    titulo: 'Biblioteca Jurídica',
    categoria: 'RECURSO INCLUSO',
    badge: '+200 Títulos Premium',
    cor: 'from-primary to-rose-600',
    icon: Library,
    funcoes: [
      '+200 livros e ebooks jurídicos',
      'Resumos dos temas mais cobrados',
      'Doutrinas e clássicos do Direito',
      'Biografias de juristas históricos',
      'Leitura offline com progresso',
      'Curadoria da equipe editorial',
      'Audiobooks por capítulo',
      'Destaques e notas pessoais'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_3',
    numero: '04',
    titulo: 'Questões & Simulados',
    categoria: 'RECURSO INCLUSO',
    badge: 'Essencial',
    cor: 'from-blue-500 to-indigo-600',
    icon: GraduationCap,
    funcoes: [
      'Milhares de questões comentadas',
      'Simulados por cargo e banca',
      'Trilhas de estudo progressivas',
      'Desafios diários gamificados',
      'Cadernos de erros inteligente',
      'Estatísticas de desempenho',
      'Revisão espaçada automática',
      'Questões por área e matéria'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_4',
    numero: '05',
    titulo: 'Kit de Estudos',
    categoria: 'RECURSO INCLUSO',
    badge: 'Aceleração',
    cor: 'from-cyan-500 to-blue-500',
    icon: Sparkles,
    funcoes: [
      'Narração nativa com voz humana',
      'Milhares de Flashcards integrados',
      'Mapas mentais da legislação',
      'Simulados comentados por banca',
      'Grifos virtuais sincronizados',
      'Anotações salvas por artigo',
      'Planos de estudo personalizados',
      'Questões com gabarito comentado'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_5',
    numero: '06',
    titulo: 'Videoaulas',
    categoria: 'RECURSO INCLUSO',
    badge: 'Catálogo Premium',
    cor: 'from-emerald-500 to-teal-500',
    icon: Tv,
    funcoes: [
      'Videoaulas por lei e matéria',
      'Professores especializados',
      'Trilhas completas por cargo',
      'Anotações integradas ao vídeo',
      'Conquistas e progresso visual',
      'Velocidade de reprodução',
      'Mini-player flutuante',
      'Catálogo por concurso'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_6',
    numero: '07',
    titulo: 'Flashcards Avançado',
    categoria: 'RECURSO INCLUSO',
    badge: 'Memorização Ativa',
    cor: 'from-teal-500 to-blue-600',
    icon: Layers,
    funcoes: [
      'Flashcards por lei e matéria',
      'Decks de jurisprudência',
      'Prazos e exceções processuais',
      'Termos e classificações',
      'Filósofos e juristas históricos',
      'Cartões Cornell de revisão',
      'Desafios cronometrados',
      'Progresso por categoria'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_7',
    numero: '08',
    titulo: 'Jurisprudência',
    categoria: 'RECURSO INCLUSO',
    badge: 'STF & STJ',
    cor: 'from-emerald-500 to-teal-600',
    icon: Gavel,
    funcoes: [
      'Jurisprudência comentada por IA',
      'Pesquisas prontas organizadas',
      'Informativos STF e STJ',
      'Teses e entendimentos atuais',
      'Súmulas com explicação',
      'Busca por tema e número',
      'Favoritar decisões relevantes',
      'Conexão com artigos da lei'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_8',
    numero: '09',
    titulo: 'Peças e Petições',
    categoria: 'RECURSO INCLUSO',
    badge: 'IA Generativa',
    cor: 'from-purple-500 to-pink-600',
    icon: FileText,
    funcoes: [
      'Gerador de petições iniciais',
      'Editor jurídico completo',
      'Modelos por área e ação',
      'Revisão inteligente por IA',
      'Formatação ABNT automática',
      'Fundamentação legal sugerida',
      'Exportação em PDF',
      'Histórico de peças salvas'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_9',
    numero: '10',
    titulo: 'Resumos Jurídicos',
    categoria: 'RECURSO INCLUSO',
    badge: 'Estudo Dirigido',
    cor: 'from-orange-500 to-red-500',
    icon: BookOpen,
    funcoes: [
      'Resumos por matéria e lei',
      'Resumos de jurisprudência',
      'Texto otimizado para fixação',
      'Organização por temas',
      'Áudio dos resumos narrados',
      'Favoritar e compartilhar',
      'Atualização automática',
      'Ideal para revisão final'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_10',
    numero: '11',
    titulo: 'Podcasts Jurídicos',
    categoria: 'RECURSO INCLUSO',
    badge: 'Em Qualquer Lugar',
    cor: 'from-indigo-500 to-purple-600',
    icon: Podcast,
    funcoes: [
      'Episódios sobre legislação',
      'Comentários de atualidades',
      'Player com velocidade ajustável',
      'Reprodução em segundo plano',
      'Curadoria por área do Direito',
      'Notificação de novos episódios',
      'Acesso offline salvo no app',
      'Temas de concurso e OAB'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_11',
    numero: '12',
    titulo: 'Leis Cantadas',
    categoria: 'RECURSO INCLUSO',
    badge: 'Fixação Musical',
    cor: 'from-pink-500 to-rose-600',
    icon: Mic,
    funcoes: [
      'Artigos musicados e cantados',
      'Player com letra sincronizada',
      'Fixação auditiva da lei seca',
      'Áudios por matéria do Direito',
      'Mini-player global flutuante',
      'Reprodução contínua e offline',
      'Velocidade de reprodução',
      'Conteúdo exclusivo original'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_12',
    numero: '13',
    titulo: 'Audioaulas',
    categoria: 'RECURSO INCLUSO',
    badge: 'Estude Ouvindo',
    cor: 'from-rose-500 to-primary',
    icon: Headphones,
    funcoes: [
      'Aulas narradas profissionais',
      'Ouça em trânsito e exercícios',
      'Player com velocidade variável',
      'Progresso salvo por capítulo',
      'Conteúdo por lei e matéria',
      'Mini-player em background',
      'Download para modo offline',
      'Notificação de novos áudios'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_13',
    numero: '14',
    titulo: 'Três Poderes Ao Vivo',
    categoria: 'RECURSO INCLUSO',
    badge: 'Tempo Real',
    cor: 'from-yellow-500 to-orange-500',
    icon: Landmark,
    funcoes: [
      'Agenda da Câmara dos Deputados',
      'Pauta do Senado Federal',
      'Sessões ao vivo do STF',
      'Radar de votações do Congresso',
      'Rankings de parlamentares',
      'Proposições legislativas do dia',
      'Portais oficiais integrados',
      'Perfil detalhado por deputado'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_14',
    numero: '15',
    titulo: 'Radar Legislativo',
    categoria: 'RECURSO INCLUSO',
    badge: 'Alertas Inteligentes',
    cor: 'from-green-500 to-emerald-500',
    icon: Bell,
    funcoes: [
      'Alertas de novas leis publicadas',
      'Monitoramento por área jurídica',
      'Proposições em alta no Congresso',
      'Impacto de leis na sua área',
      'Categorias personalizáveis',
      'Notificações push em tempo real',
      'Histórico de alterações legais',
      'Radar por estado e competência'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_15',
    numero: '16',
    titulo: 'Ferramentas Pro',
    categoria: 'RECURSO INCLUSO',
    badge: 'Ecossistema',
    cor: 'from-cyan-400 to-blue-500',
    icon: Briefcase,
    funcoes: [
      'Radar de novas leis em tempo real',
      'App iOS, Android, Web e Desktop',
      'Offline Premium sem internet',
      'Zero anúncios e interrupções',
      'Suporte prioritário exclusivo',
      'Acesso antecipado a novidades',
      'Boletins legislativos diários',
      'Exportação de grifos e notas'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_16',
    numero: '17',
    titulo: 'Aprender (Trilhas)',
    categoria: 'RECURSO INCLUSO',
    badge: 'Gamificação',
    cor: 'from-violet-500 to-purple-600',
    icon: Zap,
    funcoes: [
      'Trilhas de aprendizado guiadas',
      'Teoria + questões integradas',
      'Progresso visual por módulo',
      'Desempenho e estatísticas',
      'Flashcards dentro da trilha',
      'Aulas interativas com IA',
      'Módulos por área e assunto',
      'Sistema de conquistas e XP'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_17',
    numero: '18',
    titulo: 'Modo Aula',
    categoria: 'RECURSO INCLUSO',
    badge: 'Estudo Focado',
    cor: 'from-red-500 to-orange-500',
    icon: PenTool,
    funcoes: [
      'Sessões de estudo cronometradas',
      'Aulas estruturadas por tema',
      'Chat com IA dentro da aula',
      'Avaliação inteligente ao final',
      'Progresso e sessões salvas',
      'Gráficos de desempenho',
      'Revisão de erros e acertos',
      'Metodologia de estudo ativa'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_18',
    numero: '19',
    titulo: 'Dicionário Jurídico',
    categoria: 'RECURSO INCLUSO',
    badge: 'Consulta Rápida',
    cor: 'from-rose-600 to-amber-600',
    icon: Search,
    funcoes: [
      'Termos jurídicos explicados',
      'Busca por palavra ou conceito',
      'Exemplos de uso no Direito',
      'Conexão com artigos da lei',
      'Linguagem acessível e direta',
      'Referências doutrinárias',
      'Histórico de consultas',
      'Favoritos e coleções'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_19',
    numero: '20',
    titulo: 'Gamificação & Metas',
    categoria: 'RECURSO INCLUSO',
    badge: 'Motivação Constante',
    cor: 'from-amber-500 to-orange-500',
    icon: Trophy,
    funcoes: [
      'Sistema de XP e níveis',
      'Conquistas por categoria',
      'Streak de dias consecutivos',
      'Desafios semanais exclusivos',
      'Rankings e posições',
      'Metas personalizadas',
      'Lembretes de estudo',
      'Histórico completo de progresso'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_20',
    numero: '21',
    titulo: 'Laboratório Visual',
    categoria: 'RECURSO INCLUSO',
    badge: 'Experiência Imersiva',
    cor: 'from-primary to-rose-600',
    icon: Gamepad2,
    funcoes: [
      'Artigos do Código em 3D',
      'Cenas interativas por tema',
      'Visual jurídico animado',
      'Grafo de conexões entre artigos',
      'Explicações visuais da lei',
      'Navegação imersiva',
      'Conteúdo exclusivo curado',
      'Ideal para estudo visual'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_21',
    numero: '22',
    titulo: 'Legislação Estadual',
    categoria: 'RECURSO INCLUSO',
    badge: 'Todos os Estados',
    cor: 'from-blue-500 to-indigo-600',
    icon: Map,
    funcoes: [
      'Constituições estaduais',
      'Leis orgânicas e estatutos',
      'Busca por estado e matéria',
      'Texto integral formatado',
      'Comparação entre estados',
      'Atualização automática',
      'Favoritar leis estaduais',
      'Portal oficial integrado'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_22',
    numero: '23',
    titulo: 'Notícias Jurídicas',
    categoria: 'RECURSO INCLUSO',
    badge: 'Atualidade',
    cor: 'from-cyan-500 to-blue-500',
    icon: Newspaper,
    funcoes: [
      'Feed de notícias em tempo real',
      'STF, STJ, Congresso e OAB',
      'Análise de impacto na lei',
      'Curadoria por área de atuação',
      'Notificações de breaking news',
      'Boletim matinal por WhatsApp',
      'Novidades e atualizações do app',
      'Edição diária do blog jurídico'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_23',
    numero: '24',
    titulo: 'Meu Espaço Pessoal',
    categoria: 'RECURSO INCLUSO',
    badge: 'Tudo Organizado',
    cor: 'from-emerald-500 to-teal-500',
    icon: FolderOpen,
    funcoes: [
      'Grifos e destaques unificados',
      'Anotações em um só lugar',
      'Leis e artigos favoritos',
      'Livros e filmes salvos',
      'Downloads para offline',
      'Minhas leituras em progresso',
      'Meus resumos e videoaulas',
      'Documentos pessoais na nuvem'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
  {
    id: 'feat_24',
    numero: '25',
    titulo: 'Temáticas & Filmes',
    categoria: 'RECURSO INCLUSO',
    badge: 'Cultura Jurídica',
    cor: 'from-teal-500 to-blue-600',
    icon: Globe,
    funcoes: [
      'Filmes e séries sobre Direito',
      'Ficha técnica e análise jurídica',
      'Conexão com leis e artigos',
      'Trilha de aprendizado por tema',
      'Sugestões personalizadas',
      'Avaliação e recomendação',
      'Porque assistir cada título',
      'Curadoria da equipe editorial'
    ],
    descricaoPersuasiva: '',
    impacto: 'Acesso Imediato'
  },
];
