export interface DesafioDeckPronto {
  id: string;
  area: string;
  tema: string;
  titulo: string;
  subtitulo: string;
  ordem: number;
  nivel: 'Iniciante' | 'Intermediário' | 'Avançado' | 'Especialista';
  cardsEstimados: number;
}

export interface AreaDesafioInfo {
  area: string;
  slug: string;
  descricao: string;
  decks: DesafioDeckPronto[];
}

export const DESAFIOS_DECKS_CATALOGO: AreaDesafioInfo[] = [
  {
    area: 'Direito Penal',
    slug: 'direito-penal',
    descricao: 'Princípios penais, teoria do crime, penas e crimes em espécie',
    decks: [
      {
        id: 'penal-1',
        area: 'Direito Penal',
        tema: 'Princípios do Direito Penal',
        titulo: 'Princípios Fundamentais',
        subtitulo: 'Legalidade, insignificância, proporcionalidade e anterioridade',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 25,
      },
      {
        id: 'penal-2',
        area: 'Direito Penal',
        tema: 'Aplicação da Lei Penal',
        titulo: 'Aplicação da Lei Penal',
        subtitulo: 'Lei penal no tempo, no espaço, ultratividade e extraterritorialidade',
        ordem: 2,
        nivel: 'Iniciante',
        cardsEstimados: 30,
      },
      {
        id: 'penal-3',
        area: 'Direito Penal',
        tema: 'Teoria do Crime',
        titulo: 'Fato Típico & Conduta',
        subtitulo: 'Elemento subjetivo, dolo, culpa, nexo de causalidade e tipicidade',
        ordem: 3,
        nivel: 'Intermediário',
        cardsEstimados: 35,
      },
      {
        id: 'penal-4',
        area: 'Direito Penal',
        tema: 'Ilicitude e Culpabilidade',
        titulo: 'Ilicitude & Culpabilidade',
        subtitulo: 'Excludentes de ilicitude, imputabilidade e exigibilidade de conduta diversa',
        ordem: 4,
        nivel: 'Intermediário',
        cardsEstimados: 35,
      },
      {
        id: 'penal-5',
        area: 'Direito Penal',
        tema: 'Concurso de Pessoas e Penas',
        titulo: 'Concurso de Pessoas & Penas',
        subtitulo: 'Coautoria, participação, dosimetria da pena e regimes prisionais',
        ordem: 5,
        nivel: 'Avançado',
        cardsEstimados: 40,
      },
      {
        id: 'penal-6',
        area: 'Direito Penal',
        tema: 'Extinção da Punibilidade',
        titulo: 'Extinção da Punibilidade',
        subtitulo: 'Prescrição da pretensão punitiva e executória, decadência e perdão',
        ordem: 6,
        nivel: 'Avançado',
        cardsEstimados: 30,
      },
      {
        id: 'penal-7',
        area: 'Direito Penal',
        tema: 'Crimes Contra a Pessoa',
        titulo: 'Crimes Contra a Pessoa',
        subtitulo: 'Homicídio, lesão corporal, crimes contra a honra e liberdade',
        ordem: 7,
        nivel: 'Especialista',
        cardsEstimados: 45,
      },
      {
        id: 'penal-8',
        area: 'Direito Penal',
        tema: 'Crimes Contra O Patrimônio',
        titulo: 'Crimes Contra o Patrimônio',
        subtitulo: 'Furto, roubo, extorsão, estelionato e apropriação indébita',
        ordem: 8,
        nivel: 'Especialista',
        cardsEstimados: 45,
      },
      {
        id: 'penal-9',
        area: 'Direito Penal',
        tema: 'Crimes Contra a Administração Pública',
        titulo: 'Crimes Contra a Administração',
        subtitulo: 'Peculato, concussão, corrupção passiva e ativa, prevaricação',
        ordem: 9,
        nivel: 'Especialista',
        cardsEstimados: 40,
      },
    ],
  },
  {
    area: 'Direito Constitucional',
    slug: 'direito-constitucional',
    descricao: 'Fundamentos da República, direitos individuais, poderes e controle',
    decks: [
      {
        id: 'const-1',
        area: 'Direito Constitucional',
        tema: 'Teoria da Constituição',
        titulo: 'Poder Constituinte',
        subtitulo: 'Conceito, classificação das normas e aplicabilidade',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 25,
      },
      {
        id: 'const-2',
        area: 'Direito Constitucional',
        tema: 'Direitos e Garantias Fundamentais',
        titulo: 'Direitos Individuais & Coletivos',
        subtitulo: 'Artigo 5º, remédios constitucionais e tratados internacionais',
        ordem: 2,
        nivel: 'Iniciante',
        cardsEstimados: 40,
      },
      {
        id: 'const-3',
        area: 'Direito Constitucional',
        tema: 'Direitos Sociais e Nacionalidade',
        titulo: 'Direitos Sociais & Políticos',
        subtitulo: 'Nacionalidade, elegibilidade, partidos e direitos sociais',
        ordem: 3,
        nivel: 'Intermediário',
        cardsEstimados: 30,
      },
      {
        id: 'const-4',
        area: 'Direito Constitucional',
        tema: 'Organização do Estado',
        titulo: 'Federação & Competências',
        subtitulo: 'União, Estados, Municípios e repartição de competências legislativas',
        ordem: 4,
        nivel: 'Intermediário',
        cardsEstimados: 35,
      },
      {
        id: 'const-5',
        area: 'Direito Constitucional',
        tema: 'Poder Legislativo',
        titulo: 'Processo Legislativo',
        subtitulo: 'Emendas à CF, leis complementares, medidas provisórias e CPIs',
        ordem: 5,
        nivel: 'Avançado',
        cardsEstimados: 35,
      },
      {
        id: 'const-6',
        area: 'Direito Constitucional',
        tema: 'Poder Judiciário',
        titulo: 'Poder Judiciário & Funções',
        subtitulo: 'Estrutura, garantias da magistratura, CNJ e Ministério Público',
        ordem: 6,
        nivel: 'Avançado',
        cardsEstimados: 40,
      },
      {
        id: 'const-7',
        area: 'Direito Constitucional',
        tema: 'Controle de Constitucionalidade',
        titulo: 'Controle de Constitucionalidade',
        subtitulo: 'Controle difuso, concentrado (ADI, ADC, ADPF, ADO) e súmulas vinculantes',
        ordem: 7,
        nivel: 'Especialista',
        cardsEstimados: 50,
      },
    ],
  },
  {
    area: 'Direito Civil',
    slug: 'direito-civil',
    descricao: 'Pessoas, bens, negócios jurídicos, obrigações, contratos e família',
    decks: [
      {
        id: 'civil-1',
        area: 'Direito Civil',
        tema: 'Pessoas no Código Civil',
        titulo: 'Parte Geral: Pessoas & Capacidade',
        subtitulo: 'Personalidade jurídica, capacidade civil, direitos da personalidade',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 30,
      },
      {
        id: 'civil-2',
        area: 'Direito Civil',
        tema: 'Bens e Negócios Jurídicos',
        titulo: 'Bens & Negócio Jurídico',
        subtitulo: 'Classificação dos bens, defeitos do negócio e nulidades',
        ordem: 2,
        nivel: 'Iniciante',
        cardsEstimados: 35,
      },
      {
        id: 'civil-3',
        area: 'Direito Civil',
        tema: 'Prescrição e Decadência',
        titulo: 'Prescrição & Decadência',
        subtitulo: 'Prazos gerais e especiais, causas de suspensão e interrupção',
        ordem: 3,
        nivel: 'Intermediário',
        cardsEstimados: 25,
      },
      {
        id: 'civil-4',
        area: 'Direito Civil',
        tema: 'Direito das Obrigações',
        titulo: 'Teoria Geral das Obrigações',
        subtitulo: 'Dar, fazer, não fazer, solidariedade, mora e pagamento',
        ordem: 4,
        nivel: 'Intermediário',
        cardsEstimados: 40,
      },
      {
        id: 'civil-5',
        area: 'Direito Civil',
        tema: 'Contratos em Geral',
        titulo: 'Teoria Geral dos Contratos',
        subtitulo: 'Função social, boa-fé objetiva, vícios redibitórios e evicção',
        ordem: 5,
        nivel: 'Avançado',
        cardsEstimados: 35,
      },
      {
        id: 'civil-6',
        area: 'Direito Civil',
        tema: 'Responsabilidade Civil',
        titulo: 'Responsabilidade Civil',
        subtitulo: 'Dano moral, material, teoria do risco, nexo causal e culpa',
        ordem: 6,
        nivel: 'Avançado',
        cardsEstimados: 35,
      },
      {
        id: 'civil-7',
        area: 'Direito Civil',
        tema: 'Direito das Coisas',
        titulo: 'Direitos Reais & Posse',
        subtitulo: 'Posse, usucapião, propriedade, condomínio e direitos de vizinhança',
        ordem: 7,
        nivel: 'Especialista',
        cardsEstimados: 40,
      },
      {
        id: 'civil-8',
        area: 'Direito Civil',
        tema: 'Direito de Família e Sucessões',
        titulo: 'Família & Sucessões',
        subtitulo: 'Casamento, união estável, alimentos, herança e testamento',
        ordem: 8,
        nivel: 'Especialista',
        cardsEstimados: 40,
      },
    ],
  },
  {
    area: 'Direito Administrativo',
    slug: 'direito-administrativo',
    descricao: 'Princípios públicos, atos, poderes, licitações e improbidade',
    decks: [
      {
        id: 'adm-1',
        area: 'Direito Administrativo',
        tema: 'Administração Pública',
        titulo: 'Princípios & Organização',
        subtitulo: 'LIMPE, desconcentração, descentralização e administração indireta',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 30,
      },
      {
        id: 'adm-2',
        area: 'Direito Administrativo',
        tema: 'Poderes Administrativos',
        titulo: 'Poderes da Administração',
        subtitulo: 'Poder vinculado, discricionário, hierárquico, disciplinar e de polícia',
        ordem: 2,
        nivel: 'Iniciante',
        cardsEstimados: 30,
      },
      {
        id: 'adm-3',
        area: 'Direito Administrativo',
        tema: 'Atos Administrativos',
        titulo: 'Teoria dos Atos Administrativos',
        subtitulo: 'Requisitos, atributos (presunção, autoexecutoriedade), anulação e revogação',
        ordem: 3,
        nivel: 'Intermediário',
        cardsEstimados: 35,
      },
      {
        id: 'adm-4',
        area: 'Direito Administrativo',
        tema: 'Licitações e Contratos',
        titulo: 'Licitações (Lei 14.133/21)',
        subtitulo: 'Modalidades, critérios de julgamento, dispensa e inexigibilidade',
        ordem: 4,
        nivel: 'Avançado',
        cardsEstimados: 45,
      },
      {
        id: 'adm-5',
        area: 'Direito Administrativo',
        tema: 'Improbidade Administrativa',
        titulo: 'Improbidade Administrativa',
        subtitulo: 'Lei 8.429/92 com as alterações da Lei 14.230/21 e dolo específico',
        ordem: 5,
        nivel: 'Avançado',
        cardsEstimados: 35,
      },
      {
        id: 'adm-6',
        area: 'Direito Administrativo',
        tema: 'Processo Administrativo',
        titulo: 'Processo Administrativo & Resp.',
        subtitulo: 'Lei 9.784/99, recursos, prazos e responsabilidade civil objetiva do Estado',
        ordem: 6,
        nivel: 'Especialista',
        cardsEstimados: 35,
      },
    ],
  },
  {
    area: 'Direito Tributário',
    slug: 'direito-tributario',
    descricao: 'Sistema tributário, impostos, obrigação e crédito tributário',
    decks: [
      {
        id: 'trib-1',
        area: 'Direito Tributário',
        tema: 'Competência Tributária',
        titulo: 'Competência & Princípios',
        subtitulo: 'Legalidade, anterioridade, irretroatividade e imunidades constitucionais',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 30,
      },
      {
        id: 'trib-2',
        area: 'Direito Tributário',
        tema: 'Espécies Tributárias',
        titulo: 'Tributos em Espécie',
        subtitulo: 'Impostos, taxas, contribuições de melhoria e empréstimos compulsórios',
        ordem: 2,
        nivel: 'Iniciante',
        cardsEstimados: 30,
      },
      {
        id: 'trib-3',
        area: 'Direito Tributário',
        tema: 'Obrigação e Crédito Tributário',
        titulo: 'Obrigação & Fato Gerador',
        subtitulo: 'Sujeito ativo e passivo, solidariedade e capacidade tributária',
        ordem: 3,
        nivel: 'Intermediário',
        cardsEstimados: 35,
      },
      {
        id: 'trib-4',
        area: 'Direito Tributário',
        tema: 'Hipóteses de Extinção do Crédito Tributário',
        titulo: 'Extinção do Crédito',
        subtitulo: 'Pagamento, compensação, decadência, prescrição e remissão',
        ordem: 4,
        nivel: 'Avançado',
        cardsEstimados: 40,
      },
      {
        id: 'trib-5',
        area: 'Direito Tributário',
        tema: 'Processo Tributário',
        titulo: 'Processo Judicial Tributário',
        subtitulo: 'Execução fiscal, embargos, exceção de pré-executividade e mandado de segurança',
        ordem: 5,
        nivel: 'Especialista',
        cardsEstimados: 40,
      },
    ],
  },
  {
    area: 'Direito do Trabalho',
    slug: 'direito-do-trabalho',
    descricao: 'Relações de emprego, salário, jornada, rescisão e direitos coletivos',
    decks: [
      {
        id: 'trab-1',
        area: 'Direito do Trabalho',
        tema: 'Introdução Ao Direito Coletivo do Trabalho',
        titulo: 'Princípios & Relação de Emprego',
        subtitulo: 'Habitualidade, subordinação, onerosidade e pessoalidade',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 25,
      },
      {
        id: 'trab-2',
        area: 'Direito do Trabalho',
        tema: 'Reforma Trabalhista',
        titulo: 'Contrato de Trabalho & Reforma',
        subtitulo: 'Teletrabalho, trabalho intermitente e terceirização',
        ordem: 2,
        nivel: 'Intermediário',
        cardsEstimados: 35,
      },
      {
        id: 'trab-3',
        area: 'Direito do Trabalho',
        tema: 'Duração do Trabalho',
        titulo: 'Jornada & Remuneração',
        subtitulo: 'Horas extras, adicionais noturno, insalubridade, periculosidade e gorjetas',
        ordem: 3,
        nivel: 'Avançado',
        cardsEstimados: 35,
      },
      {
        id: 'trab-4',
        area: 'Direito do Trabalho',
        tema: 'Rescisão do Contrato',
        titulo: 'Término do Contrato & Verbas',
        subtitulo: 'Demissão com e sem justa causa, rescisão indireta e acordo comum',
        ordem: 4,
        nivel: 'Especialista',
        cardsEstimados: 35,
      },
    ],
  },
  {
    area: 'Direito Processual Civil',
    slug: 'direito-processual-civil',
    descricao: 'CPC/15, jurisdição, petição inicial, tutelas provisórias e recursos',
    decks: [
      {
        id: 'cpc-1',
        area: 'Direito Processual Civil',
        tema: 'Normas Fundamentais do Processo Civil',
        titulo: 'Normas Fundamentais & Competência',
        subtitulo: 'Boa-fé, cooperação, contraditório substancial e competência',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 30,
      },
      {
        id: 'cpc-2',
        area: 'Direito Processual Civil',
        tema: 'Petição Inicial e Citação',
        titulo: 'Petição Inicial & Resposta do Réu',
        subtitulo: 'Requisitos, indeferimento, contestação e reconvenção',
        ordem: 2,
        nivel: 'Intermediário',
        cardsEstimados: 35,
      },
      {
        id: 'cpc-3',
        area: 'Direito Processual Civil',
        tema: 'Tutela Provisória',
        titulo: 'Tutelas Provisórias',
        subtitulo: 'Tutela de urgência (antecipada e cautelar) e tutela da evidência',
        ordem: 3,
        nivel: 'Avançado',
        cardsEstimados: 35,
      },
      {
        id: 'cpc-4',
        area: 'Direito Processual Civil',
        tema: 'Recursos no CPC',
        titulo: 'Teoria Geral dos Recursos',
        subtitulo: 'Apelação, agravo de instrumento, embargos de declaração e recurso especial',
        ordem: 4,
        nivel: 'Especialista',
        cardsEstimados: 45,
      },
    ],
  },
  {
    area: 'Direito Processual Penal',
    slug: 'direito-processual-penal',
    descricao: 'Inquérito policial, ação penal, provas, prisões cautelares e recursos',
    decks: [
      {
        id: 'cpp-1',
        area: 'Direito Processual Penal',
        tema: 'Inquérito Policial',
        titulo: 'Inquérito Policial',
        subtitulo: 'Características, prazos, arquivamento e juiz das garantias',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 30,
      },
      {
        id: 'cpp-2',
        area: 'Direito Processual Penal',
        tema: 'Ação Penal',
        titulo: 'Ação Penal',
        subtitulo: 'Pública incondicionada, condicionada e privada, princípios e legitimidade',
        ordem: 2,
        nivel: 'Intermediário',
        cardsEstimados: 30,
      },
      {
        id: 'cpp-3',
        area: 'Direito Processual Penal',
        tema: 'Prisões e Medidas Cautelares',
        titulo: 'Prisões Cautelares & Liberdade',
        subtitulo: 'Flagrante, preventiva, temporária e audiência de custódia',
        ordem: 3,
        nivel: 'Avançado',
        cardsEstimados: 40,
      },
      {
        id: 'cpp-4',
        area: 'Direito Processual Penal',
        tema: 'Recursos Criminais',
        titulo: 'Tribunal do Júri & Recursos',
        subtitulo: 'Fases do júri, apelação criminal, RESE e Habeas Corpus',
        ordem: 4,
        nivel: 'Especialista',
        cardsEstimados: 45,
      },
    ],
  },
  {
    area: 'Direito Empresarial',
    slug: 'direito-empresarial',
    descricao: 'Teoria da empresa, sociedades limitadas e anônimas, títulos e falência',
    decks: [
      {
        id: 'emp-1',
        area: 'Direito Empresarial',
        tema: 'Teoria da Empresa',
        titulo: 'Empresário & Estabelecimento',
        subtitulo: 'Conceito de empresário, impedimentos, registro e trespasse',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 25,
      },
      {
        id: 'emp-2',
        area: 'Direito Empresarial',
        tema: 'Direito Societário',
        titulo: 'Sociedades Limitadas & S/A',
        subtitulo: 'Contrato social, quotas, capital social e desconsideração da personalidade',
        ordem: 2,
        nivel: 'Intermediário',
        cardsEstimados: 35,
      },
      {
        id: 'emp-3',
        area: 'Direito Empresarial',
        tema: 'Recuperação Judicial e Falência',
        titulo: 'Falência & Recuperação Judicial',
        subtitulo: 'Lei 11.101/05, requisitos, plano de recuperação e ordem de créditos',
        ordem: 3,
        nivel: 'Avançado',
        cardsEstimados: 40,
      },
    ],
  },
  {
    area: 'Direito Previdenciário',
    slug: 'direito-previdenciario',
    descricao: 'Seguridade social, RGPS, benefícios, aposentadorias e custeio',
    decks: [
      {
        id: 'prev-1',
        area: 'Direito Previdenciário',
        tema: 'Seguridade Social',
        titulo: 'Princípios da Seguridade',
        subtitulo: 'Saúde, previdência e assistência social, princípios constitucionais',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 25,
      },
      {
        id: 'prev-2',
        area: 'Direito Previdenciário',
        tema: 'Segurados do RGPS',
        titulo: 'Segurados & Dependentes',
        subtitulo: 'Obrigatórios, facultativos, classes de dependentes e período de graça',
        ordem: 2,
        nivel: 'Intermediário',
        cardsEstimados: 30,
      },
      {
        id: 'prev-3',
        area: 'Direito Previdenciário',
        tema: 'Benefícios Previdenciários',
        titulo: 'Aposentadorias & Benefícios',
        subtitulo: 'Regras de transição da EC 103/19, pensão por morte e auxílios',
        ordem: 3,
        nivel: 'Avançado',
        cardsEstimados: 40,
      },
    ],
  },
  {
    area: 'Direito Ambiental',
    slug: 'direito-ambiental',
    descricao: 'Princípios ambientais, PNMA, licenciamento e crimes ambientais',
    decks: [
      {
        id: 'amb-1',
        area: 'Direito Ambiental',
        tema: 'Princípios do Direito Ambiental',
        titulo: 'Princípios Fundamentais',
        subtitulo: 'Prevenção, precaução, poluidor-pagador e desenvolvimento sustentável',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 25,
      },
      {
        id: 'amb-2',
        area: 'Direito Ambiental',
        tema: 'Política Nacional do Meio Ambiente',
        titulo: 'Licenciamento & Crimes Ambientais',
        subtitulo: 'SISNAMA, EIA/RIMA, Lei 9.605/98 e responsabilidade da pessoa jurídica',
        ordem: 2,
        nivel: 'Intermediário',
        cardsEstimados: 35,
      },
    ],
  },
  {
    area: 'Direitos Humanos',
    slug: 'direitos-humanos',
    descricao: 'Teoria geral, sistema global da ONU e sistema interamericano',
    decks: [
      {
        id: 'dh-1',
        area: 'Direitos Humanos',
        tema: 'Teoria Geral dos Direitos Humanos',
        titulo: 'Gerações & Tratados',
        subtitulo: 'Dimensões dos direitos humanos, incorporação e status supralegal',
        ordem: 1,
        nivel: 'Iniciante',
        cardsEstimados: 25,
      },
      {
        id: 'dh-2',
        area: 'Direitos Humanos',
        tema: 'Sistema Interamericano de Direitos Humanos',
        titulo: 'Sistema Interamericano',
        subtitulo: 'Pacto de San José, Comissão e Corte Interamericana de Direitos Humanos',
        ordem: 2,
        nivel: 'Intermediário',
        cardsEstimados: 30,
      },
    ],
  },
];

/** Todos os decks em lista plana para contagem global. */
export const TODOS_DESAFIOS_DECKS: DesafioDeckPronto[] = DESAFIOS_DECKS_CATALOGO.flatMap(a => a.decks);

/** Helper para obter decks de uma determinada área. */
export function getDecksPorArea(areaNome: string): DesafioDeckPronto[] {
  return DESAFIOS_DECKS_CATALOGO.find(a => a.area.toLowerCase() === areaNome.toLowerCase())?.decks || [];
}

/** Mapa real de quantidade de temas (desafios) por área cadastrada no Supabase */
export const AREA_TEMAS_COUNT_MAP: Record<string, number> = {
  'Direito Tributário': 34,
  'Direito Penal': 46,
  'Direito Processual Civil': 52,
  'Direito Civil': 55,
  'Direito Constitucional': 39,
  'Direito Previdenciário': 16,
  'Direito Processual do Trabalho': 11,
  'Direito do Trabalho': 28,
  'Direito Administrativo': 25,
  'Direito Processual Penal': 21,
  'Direito Empresarial': 13,
  'Teoria e Filosofia do Direito': 11,
  'Direito Financeiro': 12,
  'Lei Penal Especial': 14,
  'Direitos Humanos': 6,
  'Direito Eleitoral': 5,
  'Direito Urbanístico': 5,
  'Formação Complementar': 5,
  'Prática Profissional': 8,
  'Políticas Públicas': 12,
  'Direito Desportivo': 2,
  'Filosofia do Direito': 5,
  'Direito Concorrencial': 7,
  'Revisão OAB': 12,
  'Direito Internacional Público': 9,
  'Português': 10,
  'Direito Ambiental': 7,
  'Pesquisa Científica': 2,
  'Direito Internacional Privado': 1,
};

/** Total real de desafios (temas) disponíveis em todo o aplicativo */
export const TOTAL_DESAFIOS_COUNT = 473;

