INSERT INTO blog_edicao_posts (id, titulo, categoria, resumo, autor, tempo_leitura_min, data_publicacao, imagem_url, conteudo_md) VALUES
('art-curio-01', 'Esperança Garcia: A Primeira Advogada do Brasil e Sua Petição Histórica de 1770', 'Curiosidades', 'Conheça a história da mulher negra escravizada no Piauí que escreveu uma carta de denúncia de maus-tratos reconhecida pela OAB como a primeira petição jurídica.', 'Redação Estudos Jurídicos', 9, '2026-08-05', 'https://dnjrgpldcwcpoywamorr.supabase.co/storage/v1/object/public/blog-capas/esperanca-garcia.png', $md$Em 6 de setembro de 1770, a mulher negra escravizada **Esperança Garcia** redigiu uma petição ao Governador da Capitania do Piauí denunciando agressões físicas a si e aos seus filhos.

---

> 📜 **O Reconhecimento da OAB**:
> O Conselho Federal da OAB reconheceu formalmente Esperança Garcia como a **primeira advogada do Brasil**, transformando a data de sua petição no Dia Estadual da Consciência Negra no Piauí.$md$),
('art-curio-02', 'O Código de Hammurabi: Olho por Olho e as Origens das Leis Escritas', 'Curiosidades', 'Descubra como o rei babilônio gravou em diorito negro o primeiro código legal abrangente da história e a Lei do Talião (*Lex Talionis*).', 'Redação Estudos Jurídicos', 9, '2026-08-04', 'https://dnjrgpldcwcpoywamorr.supabase.co/storage/v1/object/public/blog-capas/curiosidades.png', $md$Esculpido por volta de 1750 a.C., o **Código de Hammurabi** continha 282 leis gravadas em estela de pedra, estabelecendo a premissa de que a norma jurídica deve ser pública e igual para todos.$md$),
('art-curio-03', 'Julgamentos Bizarros da Idade Média: Quando Animais Iam ao Banco dos Réus', 'Curiosidades', 'Porcos, roedores e insetos com defensores nomeados pelo tribunal: como funcionavam os processos criminais contra animais na Europa medieval.', 'Redação Estudos Jurídicos', 8, '2026-08-03', 'https://dnjrgpldcwcpoywamorr.supabase.co/storage/v1/object/public/blog-capas/curiosidades.png', $md$Na Idade Média europeia, animais acusados de causar danos ou mortes eram julgados perante tribunais seculares ou eclesiásticos com direito a advogado de defesa e rito solene.$md$),
('art-curio-04', 'Erro de Tradução na Constituição de 1824: O Impacto nos Poderes da República', 'Curiosidades', 'Descubra como equívocos de tradução de textos do francês e inglês quase alteraram a redação de dispositivos da primeira Constituição do Brasil.', 'Redação Estudos Jurídicos', 8, '2026-08-02', 'https://dnjrgpldcwcpoywamorr.supabase.co/storage/v1/object/public/blog-capas/curiosidades.png', $md$Durante a elaboração da Constituição Imperial de 1824, debates intensos ocorreram sobre termos jurídicos importados do constitucionalismo liberal europeu.$md$),
('art-curio-05', 'Origem da Beca e do Termo Doutor no Direito: Tradições e Mitos Jurídicos', 'Curiosidades', 'Desmistifique o Decreto Imperial de 1827 e entenda as origens históricas da vestes talares dos tribunais e títulos jurídicos.', 'Redação Estudos Jurídicos', 8, '2026-08-01', 'https://dnjrgpldcwcpoywamorr.supabase.co/storage/v1/object/public/blog-capas/curiosidades.png', $md$A tradição das vestes talares (beca) remonta às universidades medievais, simbolizando a imparcialidade e solemnidade do ato de julgar.$md$);