-- Migration: Add missing indexes on user_id columns for RLS performance
-- Generated automatically by audit_indexes.cjs
-- Uses DO block to safely skip tables that may not exist

DO $$
DECLARE
  cmds text[] := ARRAY[
    'CREATE INDEX IF NOT EXISTS idx_user_preferences_user_id ON public.user_preferences (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_anotacoes_artigo_user_id ON public.anotacoes_artigo (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_biblioteca_livros_user_id ON public.biblioteca_livros (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_simulados_user_id ON public.simulados (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_mensagens_suporte_user_id ON public.mensagens_suporte (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_newsletter_subscriptions_user_id ON public.newsletter_subscriptions (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_biblioteca_favoritos_user_id ON public.biblioteca_favoritos (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_assinaturas_user_id ON public.assinaturas (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_push_campaigns_created_by ON public.push_campaigns (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_push_campaigns_user_id ON public.push_campaigns (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_push_events_user_id ON public.push_events (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_noticias_comentarios_user_id ON public.noticias_comentarios (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_mentor_perfil_user_id ON public.mentor_perfil (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_mentor_mensagens_user_id ON public.mentor_mensagens (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_reels_comentarios_user_id ON public.reels_comentarios (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_reels_curtidas_user_id ON public.reels_curtidas (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_tematica_comentarios_user_id ON public.tematica_comentarios (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_tematica_favoritos_user_id ON public.tematica_favoritos (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_tematica_watchlist_user_id ON public.tematica_watchlist (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_biblioteca_leitura_progresso_user_id ON public.biblioteca_leitura_progresso (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_videoaula_reacoes_user_id ON public.videoaula_reacoes (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_videoaula_comentarios_user_id ON public.videoaula_comentarios (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_hero_home_images_created_by ON public.hero_home_images (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_home_curiosidades_created_by ON public.home_curiosidades (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_horus_whatsapp_users_user_id ON public.horus_whatsapp_users (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_horus_verification_codes_user_id ON public.horus_verification_codes (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_horus_conversations_user_id ON public.horus_conversations (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_horus_campaigns_created_by ON public.horus_campaigns (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_horus_proactive_log_user_id ON public.horus_proactive_log (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_boletim_likes_user_id ON public.boletim_likes (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_boletim_comentarios_user_id ON public.boletim_comentarios (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_blog_post_views_user_id ON public.blog_post_views (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_blog_post_likes_user_id ON public.blog_post_likes (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_blog_post_comments_user_id ON public.blog_post_comments (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_assinatura_cancelamentos_user_id ON public.assinatura_cancelamentos (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_notification_read_state_user_id ON public.notification_read_state (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_ai_usage_log_user_id ON public.ai_usage_log (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_locais_avaliacoes_user_id ON public.locais_avaliacoes (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_locais_fotos_usuario_user_id ON public.locais_fotos_usuario (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_locais_selos_user_id ON public.locais_selos (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_locais_trilhas_progresso_user_id ON public.locais_trilhas_progresso (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_locais_favoritos_user_id ON public.locais_favoritos (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_biblioteca_leitura_jobs_created_by ON public.biblioteca_leitura_jobs (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_biblioteca_pdf_telemetry_user_id ON public.biblioteca_pdf_telemetry (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_search_hits_user_id ON public.search_hits (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_tematica_metricas_user_id ON public.tematica_metricas (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_audio_recordings_user_id ON public.audio_recordings (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_user_reminder_preferences_user_id ON public.user_reminder_preferences (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_trial_reminders_user_id ON public.trial_reminders (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_desktop_link_tokens_user_id ON public.desktop_link_tokens (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_user_activity_state_user_id ON public.user_activity_state (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_store_setup_progress_user_id ON public.store_setup_progress (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_apple_csr_storage_user_id ON public.apple_csr_storage (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_aprender_dominio_area_user_id ON public.aprender_dominio_area (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_chat_feedback_user_id ON public.chat_feedback (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_artigo_ai_cache_created_by ON public.artigo_ai_cache (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_artigo_ai_cache_user_id ON public.artigo_ai_cache (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_apresentacoes_narradas_created_by ON public.apresentacoes_narradas (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_apresentacoes_narradas_user_id ON public.apresentacoes_narradas (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_apresentacao_likes_user_id ON public.apresentacao_likes (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_apresentacao_favoritos_user_id ON public.apresentacao_favoritos (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_apresentacao_comentarios_user_id ON public.apresentacao_comentarios (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_user_last_location_user_id ON public.user_last_location (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_app_transfer_profiles_user_id ON public.app_transfer_profiles (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_flashcards_decks_user_id ON public.flashcards_decks (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_questoes_favoritos_user_id ON public.questoes_favoritos (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_questoes_trilha_progresso_user_id ON public.questoes_trilha_progresso (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_questoes_desafios_progresso_user_id ON public.questoes_desafios_progresso (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_questoes_lembretes_user_id ON public.questoes_lembretes (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_leis_cantadas_created_by ON public.leis_cantadas (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_resumos_cantados_created_by ON public.resumos_cantados (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_leis_cantadas_favoritos_created_by ON public.leis_cantadas_favoritos (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_leis_cantadas_reacoes_created_by ON public.leis_cantadas_reacoes (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_lei_seca_lembretes_user_id ON public.lei_seca_lembretes (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_lei_seca_favoritos_user_id ON public.lei_seca_favoritos (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_forca_progresso_user_id ON public.forca_progresso (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_forca_artigos_progresso_user_id ON public.forca_artigos_progresso (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_shared_decks_user_id ON public.shared_decks (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON public.profiles (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_study_questions_user_id ON public.study_questions (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_study_answers_user_id ON public.study_answers (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_CF88_CONSTITUICAO_FEDERAL_user_id ON public."CF88_CONSTITUICAO_FEDERAL" (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_biblioteca_imagens_user_id ON public.biblioteca_imagens (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_vade_mecum_leis_user_id ON public.vade_mecum_leis (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_kanban_proposicoes_user_id ON public.kanban_proposicoes (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_artigo_educacional_cache_user_id ON public.artigo_educacional_cache (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_noticias_juridicas_user_id ON public.noticias_juridicas (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_biblioteca_leitura_nativa_user_id ON public.biblioteca_leitura_nativa (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_feature_limits_user_id ON public.feature_limits (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_videoaula_conteudo_user_id ON public.videoaula_conteudo (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_horus_funcoes_created_by ON public.horus_funcoes (created_by)',
    'CREATE INDEX IF NOT EXISTS idx_horus_intent_logs_user_id ON public.horus_intent_logs (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_horus_phone_transfers_user_id ON public.horus_phone_transfers (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_aprender_areas_user_id ON public.aprender_areas (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_jurisprudencia_leis_map_user_id ON public.jurisprudencia_leis_map (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_praticar_desafios_cache_user_id ON public.praticar_desafios_cache (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_dicionario_juridico_user_id ON public.dicionario_juridico (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_flashcards_areas_user_id ON public.flashcards_areas (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_flashcards_deck_itens_user_id ON public.flashcards_deck_itens (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_videoaulas_areas_direito_user_id ON public.videoaulas_areas_direito (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_questoes_cargos_user_id ON public.questoes_cargos (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_questoes_simulado_itens_user_id ON public.questoes_simulado_itens (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_questoes_trilhas_user_id ON public.questoes_trilhas (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_questoes_desafios_user_id ON public.questoes_desafios (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_lei_seca_trilhas_user_id ON public.lei_seca_trilhas (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_lei_seca_jobs_user_id ON public.lei_seca_jobs (user_id)',
    'CREATE INDEX IF NOT EXISTS idx_mensagens_suporte_respostas_user_id ON public.mensagens_suporte_respostas (user_id)'
  ];
  cmd text;
BEGIN
  FOREACH cmd IN ARRAY cmds LOOP
    BEGIN
      EXECUTE cmd;
      RAISE NOTICE 'OK: %', cmd;
    EXCEPTION WHEN undefined_table OR undefined_column THEN
      RAISE NOTICE 'SKIPPED (table/column not found): %', cmd;
    END;
  END LOOP;
END
$$;