-- Deletar obras que não têm relação com a temática jurídica
DELETE FROM public.tematica_juridica_obras
WHERE titulo IN (
  'O Senhor dos Anéis: Os Anéis de Poder',
  'Duna',
  'A Origem',
  'Loki',
  'What If...?',
  'Supergirl',
  'The Expanse',
  'O Passageiro do Futuro 2 - Dominando O Ciberespaço',
  'Batman: O Cavaleiro das Trevas',
  'Mortal Kombat',
  'Gladiador',
  'Coração Valente',
  'O Assassino: O Primeiro Alvo',
  'Mente Criminosa',
  'Ladrão de Diamantes',
  'João e Maria: Caçadores de Bruxas',
  'Friends',
  'Operação Cupido',
  'Espelho, Espelho Meu',
  'Entrando numa Fria Maior Ainda com a Família',
  'Uma Festa no Ar',
  'Clique seu Coração',
  '불새',
  'As Aventuras de Paddington 2',
  'Náufrago',
  'Perdido em Marte',
  '127 Horas',
  'A Árvore da Vida',
  'Questão de Tempo',
  'À Procura da Felicidade',
  'Gênio Indomável',
  'Uma Mente Brilhante',
  'Rocky: Um Lutador',
  'Clube da Luta',
  'Brata',
  'Inside Dubai: Playground of the Rich',
  'Undressed',
  '¿Putas o peluqueras?',
  'Приключения домовёнка'
);
